
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 77, in <module>
    for ship_id in long_targets:
NameError: name 'long_targets' is not defined

