
Turn 3
================================================================
warning: entity 0 was directed to use 1 halite to move north, but only 0 halite was available
At command 1 of 2:
>>> 1   m 0 n
    2   g


Turn 6
================================================================
warning: entity 0 was directed to use 5 halite to move north, but only 1 halite was available
At command 2 of 3:
    1   m 2 n
>>> 2   m 0 n
    3   m 4 n


Turn 8
================================================================
warning: entity 0 was directed to use 12 halite to move north, but only 11 halite was available
At command 2 of 4:
    1   m 4 n
>>> 2   m 0 n
    3   m 2 e
    4   m 5 n

warning: entity 2 was directed to use 12 halite to move east, but only 0 halite was available
At command 3 of 4:
    1   m 4 n
    2   m 0 n
>>> 3   m 2 e
    4   m 5 n


Turn 9
================================================================
warning: owned entities 4, 2 collided on cell (9, 14) as the result of moves on this turn
At command 3 of 5:
    1   m 0 n
    2   m 2 o
>>> 3   m 4 e
    4   m 5 o
    5   g


Turn 10
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 87, in <module>
    set_long_target(ship)
  File "MyBot.py", line 62, in set_long_target
    if not has_arrival_conflict(ship, cell.position):
  File "MyBot.py", line 24, in has_arrival_conflict
    for ship_id in long_targets:
RuntimeError: dictionary changed size during iteration

